dbfilename redis_queue.rdb
dir /Users/sarashaikh/Desktop/LocalRepos/hrms/frappe-bench/config/pids
pidfile /Users/sarashaikh/Desktop/LocalRepos/hrms/frappe-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /Users/sarashaikh/Desktop/LocalRepos/hrms/frappe-bench/config/redis_queue.acl
